import type { Metadata } from "next";
import { Container } from "@/components/layout/Container";
import { Button } from "@/components/ui/Button";
import styles from "./page.module.css";
export const metadata: Metadata={title:"Global Academic Review Initiative",description:"GARI invites independent academic review and critical examination of Evolution of Energy.",alternates:{canonical:"/academic-review"}};
const areas=["Conceptual coherence","Reasoning","Relation to established knowledge","Scientific and philosophical claims","Limitations and corrections","Interdisciplinary and educational relevance"];
export default function AcademicReviewPage(){return <>
<section className={styles.hero}><Container reading><p className={styles.eyebrow}>Global Academic Review Initiative</p><h1>An invitation to examine <em>Evolution of Energy</em> critically.</h1><p className={styles.lead}>GARI makes the First Canonical Edition available to scholars, researchers and educational communities for independent review, critical evaluation and consideration of possible interdisciplinary or educational relevance.</p><blockquote>GARI seeks examination, not endorsement; criticism, not confirmation; dialogue, not institutional prestige.</blockquote><div className={styles.actions}><Button href="/academic-review/request">Request an Academic Review Copy</Button><Button href="#principles" variant="secondary">Read Review Principles</Button></div></Container></section>
<section className={styles.light}><Container><p className={styles.eyebrow}>What may be examined</p><h2>Questions are welcome from more than one direction.</h2><div className={styles.cards}>{areas.map((a,i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3></article>)}</div></Container></section>
<section id="principles" className={styles.principles}><Container reading><p className={styles.eyebrow}>Review Principles</p><h2>Independent by design.</h2><h3>Independence</h3><p>Reviewers are invited to reach their own conclusions. Agreement with EOE is neither requested nor expected.</p><h3>Transparency</h3><p>Favorable, critical, negative and inconclusive observations are all legitimate parts of serious examination.</p><h3>Traceability</h3><p>Issued academic review copies may carry a unique GARI identifier so correspondence and responses can be recorded accurately.</p><h3>No implied endorsement</h3><p>Correspondence, receipt of a review copy, faculty comment, library consideration or classroom discussion does not by itself represent an institution&apos;s position.</p><h3>Revision through criticism</h3><p>Constructive criticism, corrections and identified limitations can contribute to future clarification while the First Canonical Edition remains the reference edition.</p></Container></section>
<section className={styles.process}><Container reading><p className={styles.eyebrow}>Who may request a copy?</p><h2>For genuine scholarly and educational examination.</h2><p>University faculty, researchers, departments, research centres, librarians, educators and other qualified reviewers may request an Academic Review Copy. Independent scholars are not excluded. Requests are reviewed individually and a copy is not guaranteed.</p><Button href="/academic-review/request">Request an Academic Review Copy</Button><p className={styles.disclaimer}><strong>Academic Review Disclaimer:</strong> Participation in correspondence, receipt of a review copy, provision of comments, library consideration or classroom discussion does not by itself constitute institutional endorsement, validation, peer-review certification or approval.</p></Container></section>
</>}
