import type { Metadata } from "next";
import Image from "next/image";
import { Container } from "@/components/layout/Container";
import { PersonJsonLd } from "@/components/seo/JsonLd";
import { Button } from "@/components/ui/Button";
import styles from "./page.module.css";

export const metadata: Metadata = {
  alternates: { canonical: "/author" }, title: "Sreedhar G.", description: "Meet Sreedhar G., author of Evolution of Energy." };

export default function AuthorPage(){return <><PersonJsonLd/>
<section className={styles.hero}><Container className={styles.grid}><div className={styles.photoWrap}><Image src="/author/sreedhar-g-cropperd.jpg" alt="Sreedhar G., author of Evolution of Energy" width={574} height={1216} priority sizes="(max-width: 800px) 82vw, 420px"/><span aria-hidden="true"/></div><div><p className={styles.eyebrow}>The Author</p><h1>Sreedhar G.</h1><p className={styles.lead}>A lifelong curiosity about reality, life and human understanding gradually became the journey expressed in <em>Evolution of Energy</em>.</p><blockquote>“He does not ask readers to agree with him; he invites them to observe, reflect, and continue the conversation for themselves.”</blockquote></div></Container></section>
<section className={styles.bio}><Container reading><h2>A lifetime of questions.</h2><p>Sreedhar G. was born on 6 January 1971 in India. From an early age, curiosity, observation and independent problem-solving became enduring parts of his life. His interests grew across science and mathematics, evolution and cosmology, religion and society, politics and economics, psychology and language, arts and technology, history and philosophy.</p><p>Much of this learning was self-directed. Over the years, books and later digital access allowed questions from different fields to meet within one continuing inquiry.</p><p>He served as a <strong>Sub-Divisional Engineer in the Department of Telecommunications, Government of India</strong>. With more than seven years of service still remaining, he chose voluntary retirement because professional responsibilities left too little time for the research and writing that had become central to his life.</p><p>He now lives on his pension and devotes his time to study, reflection and writing, motivated by a desire to share understanding, reduce suffering, encourage inquiry and contribute—however modestly—to a better human future.</p><p>His sensitivity to suffering extends beyond human life to animals, birds and other living beings, and to people whose voices or opportunities are easily overlooked. Family, teachers, friends, colleagues and many others who helped along the way remain an important part of the journey behind EOE.</p><div className={styles.cta}><Button href="/book">Discover the Book</Button><Button href="/explore" variant="secondary">Explore EOE</Button></div></Container></section>
</>}
